---
platform: linux

image_resource:
  type: docker-image
  source: {repository: https://harbor.h2o-2-5673.h2o.vmware.com/cf-mgmt/cf-mgmt, tag: "latest"}

inputs:
  - name: config-repo

params:
  SYSTEM_DOMAIN:
  USER_ID:
  PASSWORD:
  CONFIG_DIR:
  CLIENT_SECRET:
  LDAP_USER:
  LDAP_PASSWORD:
  LDAP_SERVER:
  LOG_LEVEL:
  CF_MGMT_COMMAND:
run:
  path: config-repo/ci/tasks/cf-mgmt.sh
