enable-delete-isolation-segments: false
enable-unassign-security-groups: false
running-security-groups:
- default_security_group
staging-security-groups:
- default_security_group
shared-domains:
  apps.h2o-2-5673.h2o.vmware.com:
    internal: false
  apps.internal:
    internal: true
enable-remove-shared-domains: true
metadata-prefix: cf-mgmt.pivotal.io
enable-service-access: true
ignore-legacy-service-access: false
service-access:
- broker: dedicated-mysql-broker
  services:
  - service: p.mysql
    all_access_plans:
    - db-small
- broker: credhub-broker
  services:
  - service: credhub
    all_access_plans:
    - default
- broker: app-autoscaler
  services:
  - service: app-autoscaler
    all_access_plans:
    - standard
- broker: nfsbroker
  services:
  - service: nfs
    all_access_plans:
    - Existing
  - service: nfs-legacy
    no_access_plans:
    - Existing
- broker: smbbroker
  services:
  - service: smb
    no_access_plans:
    - Existing
- broker: p-redis
  services:
  - service: p-redis
    all_access_plans:
    - shared-vm
- broker: redis-odb
  services:
  - service: p.redis
    all_access_plans:
    - on-demand-cache
protected-users: []
